language: android
sudo: required
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=25
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=27.0.3
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-$EMULATOR_API # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API

licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t "android-25"
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
